### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by nonon1234** [nonon1234/furima-28135#9]
# URL
https://furima-28135.herokuapp.com/

# Basic認証のIDとパスワード
ユーザー名：admin
パスワード：2222

# 出品者用のメールアドレスとパスワード
メールアドレス：test94@test
パスワード：test94

# 購入者用のメールアドレスとパスワード
メールアドレス：suzuki@test.com
パスワード：suzuki94

# 購入用カードの番号・期限・セキュリティコード
番号：4242424242424242
期限：2/22
csc ：123

**Comment by hodakaichimura** [comment]
nonon1234 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**Comment by nonon1234** [comment]
ご確認ありがとうございます！
ではこのissueはクローズとさせていただきます。
引き続きよろしくお願いいたします。
